apiVersion: v1
kind: Template
metadata:
  name: storage-test-template
parameters:
- name: PVC_TARGET
  displayName: PersistentVolumeClaim used in test
  description: Name of PVC to test 
  required: true
- name: TOOLS_IMAGE
  displayName: Tools image
  description: Pull specification for container image, for example docker.io/centos/tools, or registry.access.redhat.com/rhel7/rhel-tools 
  required: true
  value: docker.io/centos/tools
- name: NUMBER_OF_RUNS
  displayName: Number of tests
  description: Number of tests to run
  value: '1'
  required: true
- name: NUMBER_OF_CONCURRENT
  displayName: Concurrent tests
  description: Number of tests to run at the same time
  value: '1'
  required: true
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    generateName: storage-test-
  spec:
    parallelism: ${NUMBER_OF_CONCURRENT}    
    completions: ${NUMBER_OF_RUNS}
    template:         
      metadata:
        name: storage-test
      spec:
        containers:
        - name: tools-image
          image: ${TOOLS_IMAGE}
          command:
          - "/bin/bash"
          - "-c"
          - "curl -o /var/tmp/storage-test.sh -s https://raw.githubusercontent.com/edseymour/openshift-infratests/master/storage-test.sh; source /var/tmp/storage-test.sh /test"
          volumeMounts:
          - name: testdir
            mountPath: /test
        restartPolicy: OnFailure 
        volumes:
        - name: testdir
          persistentVolumeClaim:
            claimName: ${PVC_TARGET}

